dist: trusty
sudo: false
jdk:
  - oraclejdk8
git:
  depth: 3

env:
  - buildNSSC=false TERM=dumb

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew build || (exitcode=$?; find build/tests -type f | while read f; do echo -e "\033[4m$f\033[0m"; cat $f; done && return $exitcode)

before_deploy:
  if $buildNSSC; then
    cd .. &&
    git clone "https://socha-bot:$GH_TOKEN@github.com/CAU-Kiel-Tech-Inf/not-so-simple-client.git" &&
    cd not-so-simple-client &&
    ./gradlew shadowJar &&
    cd "$TRAVIS_BUILD_DIR";
  fi

deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file_glob: true
  file:
    - build/deploy/*.jar
    - build/deploy/*.zip
    - ../not-so-simple-client/*.jar
  skip_cleanup: true
  on:
    tags: true
